baseURL = 'https://nebelnite.github.io/'
languageCode = 'en-us'
title = 'Jonas B'
lastmod = true
enableGitalk = true


[params]
  author = "Jonas B"
  github = "NebelNite"
  enableGithubFollowers = true
  email = "jonas.bogensberger@htl-saalfelden.at"
  rss = true
  url = "nebelnite.github.io"
  lastmod = true
  userStatusEmoji = "😀"
  favicon = "/images/github.png"
  avatar = "/images/avatar.png"
  headerIcon = "/images/GitHub-Mark-Light-32px.png"
  location = "Austria"  
  enableGitalk = true
  github_repos = true

  

  [params.gitalk]
    clientID = "{{ getenv "GITALK_CLIENT_ID" }}"
    clientSecret = "{{ getenv "GITALK_CLIENT_SECRET" }}"
    repo = "NebelNite.github.io"
    owner = "NebelNite"
    admin = "NebelNite"
    id = "{{ .Permalink }}"
    labels = "gitalk"
    perPage = 15
    pagerDirection = "last"
    createIssueManually = true
    distractionFreeMode = false
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token"

  [[params.links]]
    title = "Link"
    href = "https://github.com/NebelNite"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[markup.goldmark.renderer]
unsafe = true


